export const FETCH_LOGIN_ERROR = "FETCH_LOGIN_ERROR";
export const FETCH_LOGIN_REQUEST = "FETCH_LOGIN_REQUEST";
export const FETCH_LOGIN_SUCCESS = "FETCH_LOGIN_SUCCESS";

export const UPDATE_LOGIN_ERROR = "UPDATE_LOGIN_ERROR";
export const UPDATE_LOGIN_REQUEST = "UPDATE_LOGIN_REQUEST";
export const UPDATE_LOGIN_SUCCESS = "UPDATE_LOGIN_SUCCESS";

export const RESTORE_LOGIN_REQUEST = "RESTORE_LOGIN_REQUEST";
export const RESTORE_LOGIN_SUCCESS = "RESTORE_LOGIN_SUCCESS";

export const FETCH_USERPROFILE_SUCCESS = "FETCH_USERPROFILE_SUCCESS";
export const FETCH_USERPROFILE_ERROR = "FETCH_USERPROFILE_ERROR";
export const FETCH_USERPROFILE_REQUEST = "FETCH_USERPROFILE_REQUEST";

export const FETCH_POSTDETAIL_SUCCESS = "FETCH_POSTDETAIL_SUCCESS";
export const FETCH_POSTDETAIL_REQUEST = "FETCH_POSTDETAIL_REQUEST";
export const FETCH_POSTDETAIL_ERROR = "FETCH_POSTDETAIL_ERROR";

export const FETCH_POSTDETAILFAVUPDATE_SUCCESS =
  "FETCH_POSTDETAILFAVUPDATE_SUCCESS";
export const FETCH_POSTDETAILFAVUPDATE_REQUEST =
  "FETCH_POSTDETAILFAVUPDATE_REQUEST";
export const FETCH_POSTDETAILFAVUPDATE_ERROR =
  "FETCH_POSTDETAILFAVUPDATE_ERROR";

export const FETCH_REVIEWLISTING_ERROR = "FETCH_REVIEWLISTING_ERROR";
export const FETCH_REVIEWLISTING_REQUEST = "FETCH_REVIEWLISTING_REQUEST";
export const FETCH_REVIEWLISTING_SUCCESS = "FETCH_REVIEWLISTING_SUCCESS";

export const FETCH_PACKAGEADD_ERROR = "FETCH_PACKAGEADD_ERROR";
export const FETCH_PACKAGEADD_REQUEST = "FETCH_PACKAGEADD_REQUEST";
export const FETCH_PACKAGEADD_SUCCESS = "FETCH_PACKAGEADD_SUCCESS";

export const FETCH_PACKAGEDELETE_ERROR = "FETCH_PACKAGEDELETE_ERROR";
export const FETCH_PACKAGEDELETE_REQUEST = "FETCH_PACKAGEDELETE_REQUEST";
export const FETCH_PACKAGEDELETE_SUCCESS = "FETCH_PACKAGEDELETE_SUCCESS";

export const FETCH_USERUPDATE_SUCCESS = "FETCH_USERUPDATE_SUCCESS";
export const FETCH_USERUPDATE_REQUEST = "FETCH_USERUPDATE_REQUEST";
export const FETCH_USERUPDATE_ERROR = "FETCH_USERUPDATE_ERROR";

export const FETCH_PACKAGEUPDATE_SUCCESS = "FETCH_PACKAGEUPDATE_SUCCESS";
export const FETCH_PACKAGEUPDATE_REQUEST = "FETCH_PACKAGEUPDATE_REQUEST";
export const FETCH_PACKAGEUPDATE_ERROR = "FETCH_PACKAGEUPDATE_ERROR";

export const FETCH_POSTLISTING_SUCCESS = "FETCH_POSTLISTING_SUCCESS";
export const FETCH_POSTLISTING_REQUEST = "FETCH_POSTLISTING_REQUEST";
export const FETCH_POSTLISTING_ERROR = "FETCH_POSTLISTING_ERROR";

export const FETCH_FILTERPOSTLISTING_SUCCESS =
  "FETCH_FILTERPOSTLISTING_SUCCESS";
export const FETCH_FILTERPOSTLISTING_REQUEST =
  "FETCH_FILTERPOSTLISTING_REQUEST";
export const FETCH_FILTERPOSTLISTING_ERROR = "FETCH_FILTERPOSTLISTING_ERROR";

export const REFRESH_POSTLISTING_REQUEST = "REFRESH_POSTLISTING_REQUEST";

export const SEARCH_POSTLISTING_REQUEST = "SEARCH_POSTLISTING_REQUEST";
export const SEARCH_POSTLISTING_ERROR = "SEARCH_POSTLISTING_ERROR";
export const SEARCH_POSTLISTING_SUCCESS = "SEARCH_POSTLISTING_SUCCESS";

export const FETCH_POSTADD_SUCCESS = "FETCH_POSTADD_SUCCESS";
export const FETCH_POSTADD_REQUEST = "FETCH_POSTADD_REQUEST";
export const FETCH_POSTADD_ERROR = "FETCH_POSTADD_ERROR";

export const FETCH_POSTDELETE_SUCCESS = "FETCH_POSTDELETE_SUCCESS";
export const FETCH_POSTDELETE_REQUEST = "FETCH_POSTDELETE_REQUEST";
export const FETCH_POSTDELETE_ERROR = "FETCH_POSTDELETE_ERROR";

export const FETCH_POSTUPDATE_SUCCESS = "FETCH_POSTUPDATE_SUCCESS";
export const FETCH_POSTUPDATE_REQUEST = "FETCH_POSTUPDATE_REQUEST";
export const FETCH_POSTUPDATE_ERROR = "FETCH_POSTUPDATE_ERROR";

export const FETCH_POSTFAVUPDATE_ERROR = "FETCH_POSTFAVUPDATE_ERROR";
export const FETCH_POSTFAVUPDATE_REQUEST = "FETCH_POSTFAVUPDATE_REQUEST";
export const FETCH_POSTFAVUPDATE_SUCCESS = "FETCH_POSTFAVUPDATE_SUCCESS";

export const FETCH_FAVADD_SUCCESS = "FETCH_FAVADD_SUCCESS";
export const FETCH_FAVADD_REQUEST = "FETCH_FAVADD_REQUEST";
export const FETCH_FAVADD_ERROR = "FETCH_FAVADD_ERROR";

export const FETCH_FAVLISTING_SUCCESS = "FETCH_FAVLISTING_SUCCESS";
export const FETCH_FAVLISTING_REQUEST = "FETCH_FAVLISTING_REQUEST";
export const FETCH_FAVLISTING_ERROR = "FETCH_FAVLISTING_ERROR";
export const REFRESH_PACKAGELISTING_REQUEST = "REFRESH_PACKAGELISTING_REQUEST";

export const SEARCH_STORELISTING_REQUEST = "SEARCH_STORELISTING_REQUEST";
export const SEARCH_STORELISTING_ERROR = "SEARCH_STORELISTING_ERROR";
export const SEARCH_STORELISTING_SUCCESS = "SEARCH_STORELISTING_SUCCESS";

export const FETCH_PACKAGEFAVUPDATE_SUCCESS = "FETCH_PACKAGEFAVUPDATE_SUCCESS";
export const FETCH_PACKAGEFAVUPDATE_ERROR = "FETCH_PACKAGEFAVUPDATE_ERROR";

// nidhi
export const FETCH_POSTCOMMENTRESET_SUCCESS = "FETCH_POSTCOMMENTRESET_SUCCESS";
export const RESET_NOTIFYLISTING = "RESET_NOTIFYLISTING";

export const FETCH_MATCHLISTING_SUCCESS = "FETCH_MATCHLISTING_SUCCESS";
export const FETCH_MATCHLISTING_REQUEST = "FETCH_MATCHLISTING_REQUEST";
export const FETCH_MATCHLISTING_ERROR = "FETCH_MATCHLISTING_ERROR";

export const FETCH_MATCHUPDATE_SUCCESS = "FETCH_MATCHUPDATE_SUCCESS";
export const FETCH_MATCHUPDATE_ERROR = "FETCH_MATCHUPDATE_ERROR";
export const FETCH_MATCHUPDATE_REQUEST = "FETCH_MATCHUPDATE_REQUEST";

export const FETCH_MATCHDELETE_SUCCESS = "FETCH_MATCHDELETE_SUCCESS";
export const FETCH_MATCHDELETE_ERROR = "FETCH_MATCHDELETE_ERROR";
export const FETCH_MATCHDELETE_REQUEST = "FETCH_MATCHDELETE_REQUEST";

export const FETCH_NOTIFYLISTING_SUCCESS = "FETCH_NOTIFYLISTING_SUCCESS";
export const FETCH_NOTIFYLISTING_REQUEST = "FETCH_NOTIFYLISTING_REQUEST";
export const FETCH_NOTIFYLISTING_ERROR = "FETCH_NOTIFYLISTING_ERROR";

export const FETCH_NOTIFYLISTUPDATE_SUCCESS = "FETCH_NOTIFYLISTUPDATE_SUCCESS";
export const FETCH_NOTIFYLISTUPDATE_REQUEST = "FETCH_NOTIFYLISTUPDATE_REQUEST";
export const FETCH_NOTIFYLISTUPDATE_ERROR = "FETCH_NOTIFYLISTUPDATE_ERROR";

// chat module

export const FETCH_CHATROOMLISTING_SUCCESS = "FETCH_CHATROOMLISTING_SUCCESS";
export const FETCH_CHATROOMLISTING_REQUEST = "FETCH_CHATROOMLISTING_REQUEST";
export const FETCH_CHATROOMLISTING_ERROR = "FETCH_CHATROOMLISTING_ERROR";

export const FETCH_CHATMESSAGELISTING_SUCCESS = "FETCH_CHATMESSAGELISTING_SUCCESS";
export const FETCH_CHATMESSAGELISTING_REQUEST = "FETCH_CHATMESSAGELISTING_REQUEST";
export const FETCH_CHATMESSAGELISTING_ERROR = "FETCH_CHATMESSAGELISTING_ERROR";


export const CREATE_CHATMESSAGE_ERROR = "CREATE_CHATMESSAGE_ERROR";
export const CREATE_CHATMESSAGE_REQUEST = "CREATE_CHATMESSAGE_REQUEST";
export const CREATE_CHATMESSAGE_SUCCESS = "CREATE_CHATMESSAGE_SUCCESS";

  
	
export const   FETCH_MATCHUSERPOSTLISTLISTING_ERROR='FETCH_MATCHUSERPOSTLISTLISTING_ERROR';
export const   FETCH_MATCHUSERPOSTLISTLISTING_REQUEST='FETCH_MATCHUSERPOSTLISTLISTING_REQUEST';
export const   FETCH_MATCHUSERPOSTLISTLISTING_SUCCESS='FETCH_MATCHUSERPOSTLISTLISTING_SUCCESS';
  
export const   FETCH_MATCHUSERPOSTLISTADD_ERROR='FETCH_MATCHUSERPOSTLISTADD_ERROR';
export const   FETCH_MATCHUSERPOSTLISTADD_REQUEST='FETCH_MATCHUSERPOSTLISTADD_REQUEST';
export const   FETCH_MATCHUSERPOSTLISTADD_SUCCESS='FETCH_MATCHUSERPOSTLISTADD_SUCCESS';

export const   FETCH_MATCHUSERPOSTLISTDELETE_ERROR='FETCH_MATCHUSERPOSTLISTDELETE_ERROR';
export const   FETCH_MATCHUSERPOSTLISTDELETE_REQUEST='FETCH_MATCHUSERPOSTLISTDELETE_REQUEST';
export const   FETCH_MATCHUSERPOSTLISTDELETE_SUCCESS='FETCH_MATCHUSERPOSTLISTDELETE_SUCCESS';

export const   FETCH_MATCHUSERPOSTLISTUPDATE_ERROR='FETCH_MATCHUSERPOSTLISTUPDATE_ERROR';
export const   FETCH_MATCHUSERPOSTLISTUPDATE_REQUEST='FETCH_MATCHUSERPOSTLISTUPDATE_REQUEST';
export const  FETCH_MATCHUSERPOSTLISTUPDATE_SUCCESS='FETCH_MATCHUSERPOSTLISTUPDATE_SUCCESS';

export const  FETCH_MATCHUSERPOSTLISTFAVUPDATE_ERROR='FETCH_MATCHUSERPOSTLISTFAVUPDATE_ERROR';
export const  FETCH_MATCHUSERPOSTLISTFAVUPDATE_SUCCESS='FETCH_MATCHUSERPOSTLISTFAVUPDATE_SUCCESS';
export const  FETCH_MATCHUSERPOSTLISTFAVUPDATE_REQUEST='FETCH_MATCHUSERPOSTLISTFAVUPDATE_REQUEST';	

export const  REFRESH_MATCHUSERPOSTLISTLISTING_REQUEST='REFRESH_MATCHUSERPOSTLISTLISTING_REQUEST';	
  
export const  FETCH_USERLISTING_SUCCESS='FETCH_USERLISTING_SUCCESS';
export const  FETCH_USERLISTING_REQUEST='FETCH_USERLISTING_REQUEST';
export const  FETCH_USERLISTING_ERROR='FETCH_USERLISTING_ERROR';	


export const  FETCH_MATCHDETAIL_REQUEST='FETCH_MATCHDETAIL_REQUEST';
export const  FETCH_MATCHDETAIL_SUCCESS='FETCH_MATCHDETAIL_SUCCESS';
export const  FETCH_MATCHDETAIL_ERROR='FETCH_MATCHDETAIL_ERROR';  
  
export const UPDATE_CHATMESSAGE_ERROR = "UPDATE_CHATMESSAGE_ERROR";
export const UPDATE_CHATMESSAGE_REQUEST = "UPDATE_CHATMESSAGE_REQUEST";
export const UPDATE_CHATMESSAGE_SUCCESS = "UPDATE_CHATMESSAGE_SUCCESS";


export const FETCH_GETNOTILISTING_SUCCESS = "FETCH_GETNOTILISTING_SUCCESS";
export const FETCH_GETNOTILISTING_REQUEST = "FETCH_GETNOTILISTING_REQUEST";
export const FETCH_GETNOTILISTING_ERROR = "FETCH_GETNOTILISTING_ERROR";


export const FETCH_PROFILEPOSTLISTING_ERROR = "FETCH_PROFILEPOSTLISTING_ERROR";
export const FETCH_PROFILEPOSTLISTING_REQUEST = "FETCH_PROFILEPOSTLISTING_REQUEST";
export const FETCH_PROFILEPOSTLISTING_SUCCESS = "FETCH_PROFILEPOSTLISTING_SUCCESS";

export const FETCH_FILTERPROFILEPOSTLISTING_SUCCESS = "FETCH_FILTERPROFILEPOSTLISTING_SUCCESS";
export const FETCH_FILTERPROFILEPOSTLISTING_REQUEST = "FETCH_FILTERPROFILEPOSTLISTING_REQUEST";
export const FETCH_FILTERPROFILEPOSTLISTING_ERROR = "FETCH_FILTERPROFILEPOSTLISTING_ERROR";

export const SEARCH_PROFILEPOSTLISTING_REQUEST = "SEARCH_PROFILEPOSTLISTING_REQUEST";
export const SEARCH_PROFILEPOSTLISTING_ERROR = "SEARCH_PROFILEPOSTLISTING_ERROR";
export const SEARCH_PROFILEPOSTLISTING_SUCCESS = "SEARCH_PROFILEPOSTLISTING_SUCCESS";
  
export const FETCH_PROFILEPOSTADD_ERROR = "FETCH_PROFILEPOSTADD_ERROR";
export const FETCH_PROFILEPOSTADD_REQUEST = "FETCH_PROFILEPOSTADD_REQUEST";
export const FETCH_PROFILEPOSTADD_SUCCESS = "FETCH_PROFILEPOSTADD_SUCCESS";

export const FETCH_PROFILEPOSTDELETE_ERROR = "FETCH_PROFILEPOSTDELETE_ERROR";
export const FETCH_PROFILEPOSTDELETE_REQUEST = "FETCH_PROFILEPOSTDELETE_REQUEST";
export const FETCH_PROFILEPOSTDELETE_SUCCESS = "FETCH_PROFILEPOSTDELETE_SUCCESS";

export const FETCH_PROFILEPOSTUPDATE_ERROR = "FETCH_PROFILEPOSTUPDATE_ERROR";
export const FETCH_PROFILEPOSTUPDATE_REQUEST = "FETCH_PROFILEPOSTUPDATE_REQUEST";
export const FETCH_PROFILEPOSTUPDATE_SUCCESS = "FETCH_PROFILEPOSTUPDATE_SUCCESS";
  
export const FETCH_PROFILEPOSTFAVUPDATE_ERROR = "FETCH_PROFILEPOSTFAVUPDATE_ERROR";
export const FETCH_PROFILEPOSTFAVUPDATE_SUCCESS = "FETCH_PROFILEPOSTFAVUPDATE_SUCCESS";
export const FETCH_PROFILEPOSTFAVUPDATE_REQUEST = "FETCH_PROFILEPOSTFAVUPDATE_REQUEST";
  
export const FETCH_PROFILEPOSTBOOKMARKUPDATE_ERROR = "FETCH_PROFILEPOSTBOOKMARKUPDATE_ERROR";
export const FETCH_PROFILEPOSTBOOKMARKUPDATE_SUCCESS = "FETCH_PROFILEPOSTBOOKMARKUPDATE_SUCCESS";
export const  FETCH_PROFILEPOSTBOOKMARKUPDATE_REQUEST = " FETCH_PROFILEPOSTBOOKMARKUPDATE_REQUEST";
  
export const FETCH_FRIENDREQUESTSEND_SUCCESS = "FETCH_FRIENDREQUESTSEND_SUCCESS";
export const FETCH_FRIENDREQUESTDELETE_SUCCESS = "FETCH_FRIENDREQUESTDELETE_SUCCESS";
export const FETCH_FRIENDREQUESTUPDATE_SUCCESS = "FETCH_FRIENDREQUESTUPDATE_SUCCESS";
  

export const UPDATE_ROOMREAD_ERROR = "UPDATE_ROOMREAD_ERROR";
export const UPDATE_ROOMREAD_SUCCESS = "UPDATE_ROOMREAD_SUCCESS";
export const UPDATE_ROOMREAD_REQUEST = "UPDATE_ROOMREAD_REQUEST";

  
  
  
	
	
	


