# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'crushd' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  #use_frameworks!

  pod 'React', :path => '../node_modules/react-native', :subspecs => [
      'Core',
      'RCTText',
      'RCTImage',
      'RCTNetwork',
      'RCTSettings',
      'DevSupport',
      'RCTAnimation',
      'RCTWebSocket', # needed for localhost testing of your app
      'CxxBridge',

      'RCTActionSheet',
      'RCTGeolocation',
      'RCTLinkingIOS',
      'RCTVibration',

      # Add any other subspecs you want to use in your project
    ]
    pod "yoga", :path => "../node_modules/react-native/ReactCommon/yoga"

    # Explicitly include Yoga if you are using RN >= 0.42.0

    # Third party deps podspec link
    pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
    pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
    pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

    #pod 'React', :path => '../node_modules/react-native'
    #pod 'React', :path => '../node_modules/react-native', :subspecs => [
    #  'DevSupport'
    #]


    # Pods for crushd 
      
    pod 'FBSDKCoreKit','~> 4.38.0'
    pod 'FBSDKLoginKit','~> 4.38.0'
    pod 'FBSDKShareKit','~> 4.38.0'
    #pod 'FBAudienceNetwork'
   #pod 'FacebookSDK' 


    pod 'Firebase/Core', '~> 5.9.0'
    pod 'Firebase/Auth', '~> 5.9.0'
    pod 'Firebase/Messaging', '~> 5.9.0'
    pod 'Firebase/Database', '~> 5.9.0'
    pod 'Firebase/Firestore', '~> 5.9.0'
    pod 'GoogleAppMeasurement', '~> 5.2.0'
   

  # Pods for testing
    #pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'
   # pod 'react-native-fcm', :path => '../node_modules/react-native-fcm'

   pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'


    pod 'react-native-geocoder', :path => '../node_modules/react-native-geocoder'

    pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

    pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'



  # Pods for crushd
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == "React"
        target.remove_from_project
      end
    end
  end

  
  target 'crushdTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'crushd-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for crushd-tvOS

  target 'crushd-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
